### PR TITLE
[ID-986] rename logback.xml

### PR DESCRIPTION
**Pull request by Shakespeared**
there was a typo in the filename, changed `lockback.xml` to `logback.xml`

### CODE REVIEW

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Review by rushtong — APPROVED** [review]
👍🏽

**Review by okotsopoulos — APPROVED** [review]
Seems reasonable -- what issue(s) did this incorrect name produce?

**Comment by Shakespeared** [comment]
> Seems reasonable -- what issue(s) did this incorrect name produce?

none that we noticed, I just happened to be poking around looking at integration tests and saw that it was named incorrectly. I think it might cause logs to get lost since it couldn't access the appender configs but I haven't verified that

**Comment by Shakespeared** [comment]
> > Seems reasonable -- what issue(s) did this incorrect name produce?
> 
> none that we noticed, I just happened to be poking around looking at integration tests and saw that it was named incorrectly. I think it might cause logs to get lost since it couldn't access the appender configs but I haven't verified that

Mostly I just thought it would be easier to just change it than make a ticket and wait for someone else to do so :)

**Pull request merged**
